spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  profiles:
    active: dev
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/practice1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  output:
    ansi:
      enabled: always
logging:
  level:
    com.ksh.exam.springpractice1: debug